export default [
    {
        id: '1',
        roleCode: 'Adjudicator',
        permissions: [
            {permissionCode: 'ActionAndSignReviewerTask'},
            {permissionCode: 'DownloadImage'},
            {permissionCode: 'ViewImageSeries'},
            {permissionCode: 'ViewTaskArtifact'}
        ]
    }, {
        id: '2',
        roleCode: 'Cardiology',
        permissions: [
            {permissionCode: 'ActionAndSignReviewerTask'},
            {permissionCode: 'DownloadImage'},
            {permissionCode: 'ViewImageSeries'},
            {permissionCode: 'ViewTaskArtifact'}
        ]
    }, {
        id: '3',
        roleCode: 'DataMgmt',
        permissions: [
            {permissionCode: 'ViewAnatomy'},
            {permissionCode: 'ViewAndRunReport'},
            {permissionCode: 'ViewDicomAnonTag'},
            {permissionCode: 'ViewModality'},
            {permissionCode: 'ViewProgram'},
            {permissionCode: 'ViewQuerySummary'},
            {permissionCode: 'ViewSequence'},
            {permissionCode: 'ViewSponsor'},
            {permissionCode: 'ViewSponsorContact'},
            {permissionCode: 'ViewStudy'}
        ]
    }, {
        id: '4',
        roleCode: 'IDM',
        permissions: [
            {permissionCode: 'ActionQuery'},
            {permissionCode: 'RunExport'},
            {permissionCode: 'RunReport'},
            {permissionCode: 'ViewImageSeries'},
            {permissionCode: 'ViewProgram'},
            {permissionCode: 'ViewQuerySummary'},
            {permissionCode: 'ViewImageSeriesQuery'},
            {permissionCode: 'ViewSiteContact'},
            {permissionCode: 'ViewSiteQuery'},
            {permissionCode: 'ViewStudy'},
            {permissionCode: 'ViewStudyDesign'},
            {permissionCode: 'ViewStudySite'},
            {permissionCode: 'ViewSubject'},
            {permissionCode: 'ViewSubjectQuery'},
            {permissionCode: 'ViewVisit'},
            {permissionCode: 'ViewVisitQuery'}
        ]
    }, {
        id: '5',
        roleCode: 'IRA / IA',
        permissions: [
            {permissionCode: 'ActionIraAndMyQcAndMyHistoricalAndErrorTask'},
            {permissionCode: 'ActionQuery'},
            {permissionCode: 'ActivateImageSeries'},
            {permissionCode: 'ActivateSiteContact'},
            {permissionCode: 'ActivateStudySite'},
            {permissionCode: 'ActivateSubject'},
            {permissionCode: 'ActivateVisit'},
            {permissionCode: 'AddImageSeries'},
            {permissionCode: 'AddProgram'},
            {permissionCode: 'AddSiteContact'},
            {permissionCode: 'AddSponsor'},
            {permissionCode: 'AddSponsorContact'},
            {permissionCode: 'AddStudy'},
            {permissionCode: 'AddStudySite'},
            {permissionCode: 'AddSubject'},
            {permissionCode: 'AddVisit'},
            {permissionCode: 'DownloadImage'},
            {permissionCode: 'EditImageSeries'},
            {permissionCode: 'EditProgram'},
            {permissionCode: 'EditSiteContact'},
            {permissionCode: 'EditSponsorContact'},
            {permissionCode: 'EditStudy'},
            {permissionCode: 'EditStudySite'},
            {permissionCode: 'EditSubject'},
            {permissionCode: 'EditVisit'},
            {permissionCode: 'EmailQueueNotification'},
            {permissionCode: 'ResendImageSeriesQuery'},
            {permissionCode: 'ResendSiteQuery'},
            {permissionCode: 'ResendSubjectQuery'},
            {permissionCode: 'ResendVisitQuery'},
            {permissionCode: 'RunReport'},
            {permissionCode: 'SendImageSeriesQuery'},
            {permissionCode: 'SendSiteQuery'},
            {permissionCode: 'SendSubjectQuery'},
            {permissionCode: 'SendVisitQuery'},
            {permissionCode: 'UploadImageSeries'},
            {permissionCode: 'ViewAnatomy'},
            {permissionCode: 'ViewAndRunReport'},
            {permissionCode: 'ViewDicomAnonTag'},
            {permissionCode: 'ViewErrorTask'},
            {permissionCode: 'ViewFailedEmailSummary'},
            {permissionCode: 'ViewImageSeries'},
            {permissionCode: 'ViewImageSeriesQuery'},
            {permissionCode: 'ViewIraTask'},
            {permissionCode: 'ViewModality'},
            {permissionCode: 'ViewMyQcTask'},
            {permissionCode: 'ViewProgram'},
            {permissionCode: 'ViewQuerySummary'},
            {permissionCode: 'ViewSequence'},
            {permissionCode: 'ViewSiteContact'},
            {permissionCode: 'ViewSiteQuery'},
            {permissionCode: 'ViewSponsor'},
            {permissionCode: 'ViewSponsorContact'},
            {permissionCode: 'ViewStudy'},
            {permissionCode: 'ViewStudyDesign'},
            {permissionCode: 'ViewStudySite'},
            {permissionCode: 'ViewSubject'},
            {permissionCode: 'ViewSubjectQuery'},
            {permissionCode: 'ViewTaskAdmin'},
            {permissionCode: 'ViewTasksPage'},
            {permissionCode: 'ViewVisit'},
            {permissionCode: 'ViewVisitQuery'}
        ]
    }, {
        id: '6',
        roleCode: 'MICO',
        permissions: [
            {permissionCode: 'ViewAnatomy'},
            {permissionCode: 'ViewAndRunReport'},
            {permissionCode: 'ViewDicomAnonTag'},
            {permissionCode: 'ViewModality'},
            {permissionCode: 'ViewProgram'},
            {permissionCode: 'ViewQuerySummary'},
            {permissionCode: 'ViewReviewerTask'},
            {permissionCode: 'ViewSequence'},
            {permissionCode: 'ViewSponsor'},
            {permissionCode: 'ViewSponsorContact'},
            {permissionCode: 'ViewStudy'},
            {permissionCode: 'ViewTasksPage'}
        ]
    }, {
        id: '7',
        roleCode: 'MICOManager',
        permissions: [
            {permissionCode: 'ActionQuery'},
            {permissionCode: 'AddSiteContact'},
            {permissionCode: 'EditSiteContact'},
            {permissionCode: 'RunReport'},
            {permissionCode: 'ViewImageSeries'},
            {permissionCode: 'ViewImageSeriesQuery'},
            {permissionCode: 'ViewSiteContact'},
            {permissionCode: 'ViewStudy'},
            {permissionCode: 'ViewStudyDesign'},
            {permissionCode: 'ViewStudySite'},
            {permissionCode: 'ViewSubject'},
            {permissionCode: 'ViewSubjectQuery'},
            {permissionCode: 'ViewVisit'},
            {permissionCode: 'ViewVisitQuery'}
        ]
    }, {
        id: '8',
        roleCode: 'Oncologist',
        permissions: [
            {permissionCode: 'ActionAndSignReviewerTask'},
            {permissionCode: 'DownloadImage'},
            {permissionCode: 'ViewImageSeries'},
            {permissionCode: 'ViewTaskArtifact'}
        ]
    }, {
        id: '9',
        roleCode: 'PM',
        permissions: [
            {permissionCode: 'ActivateProgram'},
            {permissionCode: 'AddProgram'},
            {permissionCode: 'AddSponsor'},
            {permissionCode: 'AddSponsorContact'},
            {permissionCode: 'AddStudy'},
            {permissionCode: 'EditProgram'},
            {permissionCode: 'EditSponsor'},
            {permissionCode: 'EditSponsorContact'},
            {permissionCode: 'PMDashboard'},
            {permissionCode: 'ViewAnatomy'},
            {permissionCode: 'ViewAndRunReport'},
            {permissionCode: 'ViewCentralReadResultsQueue'},
            {permissionCode: 'ViewDicomAnonTag'},
            {permissionCode: 'ViewErrorTask'},
            {permissionCode: 'ViewFailedEmailSummary'},
            {permissionCode: 'ViewIraTask'},
            {permissionCode: 'ViewModality'},
            {permissionCode: 'ViewMyQcTask'},
            {permissionCode: 'ViewProgram'},
            {permissionCode: 'ViewQuerySummary'},
            {permissionCode: 'ViewReviewerTask'},
            {permissionCode: 'ViewSequence'}
        ]
    }
]